



(define (cube x) (* x x x))

(define (p x) (- (* 3 x) (* 4 (cube x))))

(define (abs x)
  (if (< x 0)
      (- x)
      x))

(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3)))))

;;;Q1: how many times is procedure p applied when sine 12.5 is evaluated?
;;;A1: 
;   sine 12.5
;     | times = 1
;     V  
;   p(sine (/ 12.5 3)) => p(sine (4.1))
;                               |times = 2
;                               V
;   p(sine (/ 4.1 3)) => p(sine (1.3))
;                               |times = 3
;                               V
;   p(sine (/ 1.3 3) => p(sine (0.4))
;                               |times = 4
;                               V                                
;   p(sine (/ 0.4 3) => p(sine (0.1+))
;                               |times = 5
;                               V					
;   p(sine (/ 0.1+ 3) => p(sine ( one smaller than 0.1))=>the one
  
;;; Q2: what is   the order of growth in space and numbers of step used by the  
;;; process generated by the sine procedure when (sine n )is evaluated?
;;;A2 : log n
